[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
type = 'near'
id = 'near-0'
near_ibc_address = "v8.nearibc.testnet"
# rpc_addr = 'https://nd-354-497-726.p2pify.com/eedb1960b8b7f8747090aee8583d01f2'
rpc_addr = 'https://near-testnet.infura.io/v3/272532ecf0b64d7782a03db0cbcf3c30'
# rpc_addr = 'http://localhost:27030'
grpc_addr = 'http://localhost:27032'
event_source = { mode = 'push', url = 'ws://localhost:27030/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'stake' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['provider', 'channel-18'],
  ['transfer', 'channel-19'],
]

[[chains]]
id = 'otto_9109-1'
ic_endpoint = "https://ic0.app"
canister_id = "pcf3v-6iaaa-aaaag-qcuka-cai"
canister_pem = ".hermes/keys/ic.pem"
rpc_addr = 'https://gateway.testnet.octopus.network/rpc/otto/ynlx3k98x7w0otke'
grpc_addr = 'https://ynlx3k98x7w0otke.otto.gateway.testnet.octopus.network'
event_source = { mode = 'push', url = 'wss://gateway.testnet.octopus.network/rpc/otto/ynlx3k98x7w0otke/websocket', batch_delay = '500ms' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
rpc_timeout = '15s'
account_prefix = 'otto'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0, denom = 'ibc/86EDA6ABA44A1A5DF3B5A032592F8C0CCA2F8D25240664A440E647E5F46A9AD8' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['consumer', 'channel-0'],
  ['transfer', 'channel-1'],
]
