[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = false
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'near-0'
type = 'near'
near_ibc_address = 'v1.near-ibc.near'
rpc_addr = 'https://rpc.mainnet.near.org'
grpc_addr = 'http://localhost:27032'
event_source = { mode = 'pull', interval = '1000ms' }
rpc_timeout = '15s'
trusted_node = true
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'stake' }
gas_multiplier = 1.2
default_gas = 1000000
max_gas = 10000000
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '2', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['provider', 'channel-0'],
  ['transfer', 'channel-1'],
]

[[chains]]
id = 'otto_8900-1'
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
rpc_addr = 'https://gateway.mainnet.octopus.network/rpc/otto/andk2nmw198f7on2'
grpc_addr = 'https://andk2nmw198f7on2.otto.gateway.mainnet.octopus.network'
event_source = { mode = 'push', url = 'wss://gateway.mainnet.octopus.network/rpc/otto/andk2nmw198f7on2/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
trusted_node = true
account_prefix = 'otto'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 20000000000, denom = 'ibc/10FA9ADE4B0166E72C9AB4BB4ABB8BC81E41B8A198460D21139E3E1D052EF057' }
gas_multiplier = 1.2
default_gas = 1000000
max_gas = 40000000
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '2', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['consumer', 'channel-0'],
  ['transfer', 'channel-1'],
]
